version: "3.4"

services:
  main:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8003:8081
    environment:
      - DB_HOST=alles.cx
      - DB_NAME=alles
      - DB_USERNAME=username
      - DB_PASSWORD=password